INSERT INTO CNBS_DEV.dbo.Componente VALUES ('Ambiente de Control', '1', 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Compromiso con el Control Interno y Adhesión a las Políticas', '1.1', 1, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad, en conjunto con los responsables de todas las áreas y/o unidades de la entidad, debe establecer los estándares específicos de mejora continua y el cumplimiento de los objetivos del control interno', '1.1.1', '2008-11-11', '2008-11-05', 'Dario', 1, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Realizar una revisión anual del cumplimiento de los objetivos del control interno a nivel institucional y retroalimentar de sus resultados a la MAE y jefes.', '1.1.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 1, 1, 3, 3, 1, 2, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad, en conjunto con los responsables de todas las áreas y/o unidades de la entidad, debe difundir las políticas institucionales de manera formal mediante notas por escrito a todos los superiores jerárquicos, así como la publicación en la página web de la entidad a todo el personal de la institución.', '1.1.2', '2008-11-11', '2008-11-05', 'Dario', 1, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Realizar conversatorios y discutir las políticas institucionales para mejor comprensión de las mismas.', '1.1.2.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 2, 1, 4, 1, 4, 3, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Realizar exposiciones y debates las políticas institucionales para mejor comprensión de las mismas.', '1.1.2.2', '2018-11-11', 'Dario', 'dario.villalta@gmail.com', 2, 1, 4, 3, 1, 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Ambiente de Control y Valores de Integridad', '1.2', 1, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad y los responsables jerárquicos deben difundir a los servidores públicos correspondientes, las prácticas de control interno implementadas para su aplicación efectiva, cuyo cumplimiento genera confianza en las operaciones y en la información generada sobre las operaciones.', '1.2.1', '2008-11-11', '2008-11-05', 'Dario', 2, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Socializar a todo el personal los resultados de la autoevaluación de Control Interno de la dependencia.', '1.2.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 3, 1, 4, 2, 3, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Establecer  un plan o mecanismo de incentivos no materiales en la dependencia para el reconocimiento de logros alcanzados.', '1.2.1.2', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 3, 1, 2, 2, 4, 2, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad, en conjunto con los responsables de todas las áreas y/o unidades de la entidad, debe propiciar y favorecer la participación activa de los funcionarios y servidores en la generación de mecanismos para fortalecer y modelar el control interno y el funcionamiento de la institución.', '1.2.2', '2008-11-11', '2008-11-05', 'Dario', 2, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Celebrar reuniones de trabajo para analizar mejoras a los procesos o  actividades del área y dar el espacio a que todos brinden sugerencias de mejora.', '1.2.2.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 4, 1, 4, 2, 3, 2, 0, 2017);

INSERT INTO CNBS_DEV.dbo.Componente VALUES ('Evaluación de Riesgos', '2', 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Identificación y evaluación de Riesgos', '2.1', 2, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad, en conjunto con los responsables jerárquicos de las áreas y/o unidades de la entidad deben definir por escrito las funciones, facultades, roles, responsabilidades y perfiles que le corresponden a cada uno de los miembros de la entidad dentro del proceso de gestión de los riesgos institucionales.', '2.1.1', '2008-11-11', '2008-11-05', 'Dario', 3, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Realizar taller de socialización de las funciones definidas en el Sistema de Riesgos de la CNBS con la colaboración del Comité de Riesgos.', '2.1.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 5, 1, 2, 3, 1, 3, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad ejecutiva debe comunicar claramente al personal las políticas y procedimientos para “Identificación y Evaluación de los Riesgos”, así como comprobar que las mismas son conocidas y comprendidas por los servidores públicos que trabajan en la entidad.', '2.1.2', '2008-11-11', '2008-11-05', 'Dario', 3, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Solicitar al Comité de Riesgos una capacitación específica a la dependencia sobre la metodología de la “Identificación y Evaluación de los Riesgos”.', '2.1.2.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 6, 1, 2, 1, 4, 2, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad ejecutiva debe establecer y gestionar políticas y procedimientos dirigidos a identificar y evaluar los riesgos relevantes que pueden impactar negativamente o impedir el logro de los objetivos, metas, proyectos y programas propios de las unidades administrativas involucradas en su consecución, en el que debe incluir las etapas.', '2.1.3', '2008-11-11', '2008-11-05', 'Dario', 3, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Elaborar y Actualizar  las matrices de riesgos de los Manuales de Procesos de las diferentes Unidades del área, con el acompañamiento de la Dirección de Planificación y Seguridad de la Información.', '2.1.3.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 7, 1, 4, 3, 3, 2, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Socializar las matrices de riesgos elaboradas/actualizadas con los involucrados del proceso.', '2.1.3.2', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 7, 1, 3, 3, 4, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Revisar anualmente los manuales de procesos de las diferentes unidades con el acompañamiento de la Dirección de Planificación y Seguridad de la Información.', '2.1.3.3', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 7, 1, 1, 4, 4, 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Revisión de los Objetivos', '2.2', 2, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('El responsable jerárquico de la Unidad de Planificación, con apoyo del resto de los superiores jerárquicos de las diferentes áreas y/o unidades de la entidad, debe desarrollar y gestionar herramientas, procedimientos y sistemas de información y gestión que puedan ser capaces de captar, procesar y reportar en forma oportuna.', '2.2.1', '2008-11-11', '2008-11-05', 'Dario', 4, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('El responsable jerárquico de la Unidad de Planificación, con apoyo del resto de los superiores jerárquicos de las diferentes áreas y/o unidades de la entidad, debe desarrollar y gestionar herramientas, procedimientos y sistemas de información.', '2.2.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 8, 1, 3, 1, 3, 4, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Revisar y actualizar trimestralmente loón respectivas POA de la dependencia para su modificación y realizar la socialización.', '2.2.1.2', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 8, 1, 2, 3, 3, 1, 0, 2017);

INSERT INTO CNBS_DEV.dbo.Componente VALUES ('Monitoreo', '3', 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Evaluación del Desempeño Institucional', '3.1', 3, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La MAE y los superiores jerárquicos de todas las unidades deben definir los indicadores del desempeño e integrados al POA. Ampliamente difundidos en todas las unidades constituyen los puntos clave de control para evaluar el desempeño y las propuestas de mejora.', '3.1.1', '2008-11-11', '2008-11-05', 'Dario', 5, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Socializar ampliamente a todo el personal los indicadores de desempeño con los cuales es medida la gestión de la dependencia.', '3.1.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 9, 1, 4, 2, 2, 3, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Monitoreo del control interno', '3.2', 3, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La MAE tiene la responsabilidad de supervisar la eficacia del Control Interno considerando los informes de las autoevaluaciones realizadas (Ver ANEXO 1 y ANEXO 2) y los informes de la UAI, como también, tomando conocimiento y aprobando los informes periódicos de las unidades operativas y administrativas de la institución.', '3.2.1', '2008-11-11', '2008-11-05', 'Dario', 6, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Realizar seguimiento a los planes de mejoramiento de control interno y socializar con todo el personal de la dependencia los resultados de su cumplimiento.', '3.2.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 10, 1, 2, 1, 4, 4, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Reporte de Deficiencias y toma de Acciones Correctivas', '3.3', 3, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La MAE debe comunicar en forma efectiva y oportuna a las unidades relacionadas en forma directa y a sus responsables jerárquicos, las deficiencias clasificadas por unidades para corregir los procedimientos y mejorarlos, señalando el trámite administrativo a seguir, cuando corresponda.', '3.3.1', '2008-11-11', '2008-11-05', 'Dario', 7, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Socializar con todas las unidades o áreas mediante reunión de trabajo los resultados de la autoevaluación de la dependencia a fin que todos estén enterados de las notas obtenidas y de los comentarios vertidos.', '3.3.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 11, 1, 1, 4, 3, 2, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('Los responsables de las áreas o unidades a los cuales se les han comunicado las deficiencias correspondientes deben responder realizando las aclaraciones que consideren pertinentes y adjuntar planes de acción para corregir dichas deficiencias, procurando de esta forma mejorar los procesos, procedimientos y tareas relacionadas.', '3.3.2', '2008-11-11', '2008-11-05', 'Dario', 7, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Socializar con todo el personal los planes de acción formulados y aprobados para mejora de los procesos de control interno.', '3.3.2.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 12, 1, 2, 3, 3, 1, 0, 2017);
            
INSERT INTO CNBS_DEV.dbo.Componente VALUES ('Comunicación', '4', 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Archivo Institucional', '4.1', 4, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('Los responsables de las áreas o unidades a los cuales se les han comunicado las deficiencias correspondientes deben responder realizando las aclaraciones que consideren pertinentes y adjuntar planes de acción para corregir dichas deficiencias, procurando de esta forma mejorar los procesos, procedimientos y tareas relacionadas.', '4.1.1', '2008-11-11', '2008-11-05', 'Dario', 8, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Socializar con todo el personal los planes de acción formulados y aprobados para mejora de los procesos de control interno.', '4.1.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 13, 1, 1, 4, 2, 2, 0, 2017);
            
INSERT INTO CNBS_DEV.dbo.Componente VALUES ('Actividades de Control', '5', 1, 0, 2017);
    INSERT INTO CNBS_DEV.dbo.Elemento VALUES ('Archivo Institucional', '5.1', 5, 1, 0, 2017);
        INSERT INTO CNBS_DEV.dbo.Practica VALUES ('La máxima autoridad debe considerar que los sistemas de registro e información sean computarizados, manuales o una mezcla, siempre que cumplan con las siguientes características: a) Los programas informáticos, de preferencia, deben ser integrados evitando la duplicidad de registros.', '5.1.1', '2008-11-11', '2008-11-05', 'Dario', 9, 1, 0, 2017);
            INSERT INTO CNBS_DEV.dbo.Actividad VALUES ('Evaluar anualmente el funcionamiento, utilidad, contenido y vigencia de los sistemas de información implementados en su dependencia y gestionar su rediseño o eliminación de los mismos.', '5.1.1.1', '2008-11-11', 'Dario', 'dario.villalta@gmail.com', 14, 1, 1, 1, 1, 1, 0, 2017);

INSERT INTO CNBS_DEV.dbo.Departamento VALUES ('Informatica', 'dario.villalta@gmail.com', 1);
INSERT INTO CNBS_DEV.dbo.Departamento VALUES ('Comite de Etica', 'dario.villalta@gmail.com', 0);
INSERT INTO CNBS_DEV.dbo.Departamento VALUES ('Recursos Humanos', 'dario.villalta@gmail.com', 1);
INSERT INTO CNBS_DEV.dbo.Departamento VALUES ('Comite de Coordinacón', 'dario.villalta@gmail.com', 0);
INSERT INTO CNBS_DEV.dbo.Departamento VALUES ('Contabilidad', 'dario.villalta@gmail.com', 1);

INSERT INTO CNBS_DEV.dbo.UnidadMedida VALUES ('Documentos');
INSERT INTO CNBS_DEV.dbo.UnidadMedida VALUES ('Fotos');
INSERT INTO CNBS_DEV.dbo.UnidadMedida VALUES ('Libros');
INSERT INTO CNBS_DEV.dbo.UnidadMedida VALUES ('Folletos');

INSERT INTO CNBS_DEV.dbo.Producto VALUES ('Reunión');
INSERT INTO CNBS_DEV.dbo.Producto VALUES ('Folletos');
INSERT INTO CNBS_DEV.dbo.Producto VALUES ('Charla');
INSERT INTO CNBS_DEV.dbo.Producto VALUES ('Comida');